/*
 * app.h
 *
 *  Created on: Nov 20, 2025
 *      Author: jeremiahtollossa
 */

#ifndef APP_H
#define APP_H

#include "main.h"

// Pass the handles generated by main.c
void App_Initialize(UART_HandleTypeDef *huart, ADC_HandleTypeDef *hadc);
void App_MainLoop(void);

#endif





//Old app.h
/*
 * app.h
 *
 *  Created on: Jun 19, 2022
 *      Author: xl0021
 */

/*#ifndef SRC_APP_H_
#define SRC_APP_H_

#include "stm32l4xx_hal.h"


void App_Init(void);
void App_MainLoop(void);


#endif /* SRC_APP_H_ */
*/
